### ISSUE TITLE
Documentation Todo

### ISSUE THREAD

**Issue by il-steffen** [IntelLabs/kAFL#126]
Reference pages
 - [ ] add reference page explaining workdir + kafl_gui elements
 - [ ] replace "Components" section with full page SW stack overview + variants / features
 - [ ] update hypercall reference
 - [ ] explain how to sub-class kAFL: quick fork or use as ansible collection

Tutorials
- [ ] revise linux fuzzing tutorials
  - [ ] htools + sharedir
  - [ ] forkserver
  - [ ] fs_fuzzer, syscalls?
  - [ ] in-kernel agent
  - [ ] vfio patches?
- [ ] revise edk2 examples
  - [ ] dxe fuzzer
  - [ ] qemu q35?
... 

Other topics
- [ ] kafl_cov.py + ghidra / fast_matcher
- [ ] gdb / noise / single
