### ISSUE TITLE
kAFL/Nyx alignment

### ISSUE THREAD

**Issue by Wenzel** [IntelLabs/kAFL#192]
The goal of this issue is to spark the discussion on the current state of kAFL compared to the [Nyx project](https://github.com/nyx-fuzz), how we might want to align kAFL to match Nyx's future evolutions.

# TODO

- [x] Generate `cargo doc` documentation for [libnyx](https://github.com/nyx-fuzz/libnyx) (see attachments: [libnyx_doc.zip](https://github.com/IntelLabs/kAFL/files/11406091/libnyx_doc.zip))
  - [x] ensure libnyx can be compiled (https://github.com/nyx-fuzz/libnyx/pull/21, https://github.com/nyx-fuzz/libnyx/pull/20)
- [ ] Document kAFL's fuzzer interface to QEMU ([`qemu_aux_buffer.py`](https://github.com/IntelLabs/kafl.fuzzer/blob/master/kafl_fuzzer/worker/qemu_aux_buffer.py), ...)
- [ ] Document differences between kAFL and Nyx project
- [ ] Sketch out a new design for libnyx API
  - [ ] Collect requirements from all possible use cases, and consider future evolutions
    - [ ]  How to propagate kafl configuration to libnyx
  - [ ] Hold design session

cc @schumilo for the brainstorming

**Comment by Wenzel** [comment]
Updating this ticket, i've managed to write some documentation on the current Fuzzer <=> QEMU interface in kAFL:
[fuzzer_qemu_interface.zip](https://github.com/IntelLabs/kAFL/files/11903665/fuzzer_qemu_interface.zip)

We should have another quick sync on this @schumilo and determine the next steps !
