### ISSUE TITLE
optionally deploy Ghidra

### ISSUE THREAD

**Issue by il-steffen** [IntelLabs/kAFL#75]
We should probably also replace the Ghidra install script with an ansible task: https://github.com/IntelLabs/kafl.fuzzer/blob/master/scripts/ghidra_install.sh

I guess it can be installed to kafl/ folder to keep everything packaged properly. We can add a new GHIDRA_ROOT to .env and adapt the plugin runner: https://github.com/IntelLabs/kafl.fuzzer/blob/master/scripts/ghidra_run.sh

**Comment by Wenzel** [comment]
# TODO

- [ ] add ghidra role (#100 )
- [ ] remove [ghidra_install.sh](https://github.com/IntelLabs/kafl.fuzzer/blob/master/scripts/ghidra_install.sh)
- [ ] update [ghidra_run.sh](https://github.com/IntelLabs/kafl.fuzzer/blob/master/scripts/ghidra_run.sh)
